[pytest]
markers =
    test: mark a test as a test case.
    smoke: mark a test as a smoke test.
    regression: mark a test as a regression test.
    auth: mark a test as an authentication test.
    api: mark a test as an API test.
    device: mark a test as device test
    ui: mark a test as a UI test.
    performance: mark a test as a performance test.
    security: mark a test as a security test.
    integration: mark a test as an integration test.
    unit: mark a test as a unit test.
    skip: mark a test to be skipped.
