[pytest]
markers =
    test: mark a test as a test case.
    auth: mark a test as an authentication test.
    device: mark a test as device test
    audit: mark a test as audit test

python_files = test_*.py *_test.py
testpaths =
    auth
    devices
    audit
    readings
addopts = -v --tb=short